### ISSUE TITLE
Обработка ошибок на событие error от xhr

### ISSUE THREAD

**Issue by ExactlyNoSense** [V4Fire/Core#108]
Сейчас при событии `error` от `xhr` режектится именно та ошибка, которую вернуло это событие, а именно `ProgressEvent`. Т.к. она совершенно не той структуры, что `RequestError`, то мы не можем её правильно обработать. Например, обычно мы получаем статус ошибки, чтобы показать нужную модалку, но в случае `ProgressEvent` мы не можем получить статус.

Нужно привести ошибки к одному виду

**Comment by kobezzza** [comment]
Закрываю issue, т.к. не понятен её статус.
