### ISSUE TITLE
Механизм оповещений (предупреждений) клиентов

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Core#123]
Есть `deprecated` механизм, необходимо по аналогии с ним разработать `warning` механизм, который будет предупреждать пользователь о том, что они делают какую-то неоптимальную, не best practice вещь

**Comment by kobezzza** [comment]
Такой функционал оч похож на functools/not-implemented. Чтобы не копипастить нужно будет зарефакторить этот АПИ, например

```
warn({type: 'notImplemented', alternative: 'bla'})
warn({notice: 'bla bla'})
```

**Comment by kobezzza** [comment]
https://github.com/V4Fire/Core/pull/128
