### ISSUE TITLE
[Object.fastClone] Неожиданное поведение

### ISSUE THREAD

**Issue by bonkalol** [V4Fire/Core#125]
Сейчас если в `Object.fastClone` передать объект в котором строкой содержится дата, он ее преобразует в дату, кажется это может приводить к неочевидным проблемам, например:

https://github.com/V4Fire/Core/blob/5ee670d377e20a2febee1d29eb63adedb12754ea/src/core/request/response/index.ts#L255

Здесь если есть `decoder` то происходит вызов `fastClone` в этом случае, в объекте, будут объекты дат а не строки.
Если убираешь провайдер, то `fastClone` не будет вызван и соотвественно строки не будут сконвечерны, это очень неочевидное поведение при которое нужно помнить ВСЕГДА.

**Comment by bonkalol** [comment]
Возможно там в response стоит выключить reviewer чтобы не было таких неожиданностей

**Comment by kobezzza** [comment]
Доработаю после отпуска:)

**Comment by kobezzza** [comment]
fastClone поправил.

Также добавил параметр jsonReviver в core/request: по умолчанию старое поведение (строки даты в ответе сервера парсятся из JSON), чтобы не делать BR, но теперь это легко отключается.

https://github.com/V4Fire/Core/pull/127
