### ISSUE TITLE
Решить проблему с порядком проверяемых функций в `src/core/async/modules/events/index.ts:153`

### ISSUE THREAD

**Issue by Gannicus91** [V4Fire/Core#369]
Сейчас мы завязываемся на конкретный порядок, в котором проверяются функции, которую необходимо использовать для подписки на событие

```ts
						p.single && emitter.once ||
						emitter.on ||
						emitter.addListener ||
						emitter.addEventListener;
```

Разные эмиттеры имеют разный апи и нам нужно уметь выбирать корректную функцию

Например при таком вызове

```ts
const mq = globalThis.matchMedia('(prefers-color-scheme: dark)');
this.async.on(mq, 'change', ...);
```

у mq есть и `addEventListener` и `addListener`, однако `addListener` - `deprecated` и имеет другое апи и такой вызов крашится

**Comment by kobezzza** [comment]
Для решения этой проблемы, допускается в качестве эвент эмиттера передать функцию, которая будет работать как on и как off
